apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daemon-set
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/chrisXar/chrisrepo.git
    targetRevision: dev
    path: manifiestos-kubernetes/3/daemon
  destination: 
    server: https://kubernetes.default.svc
    namespace: chris

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: false
      prune: false