apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  containers:
  - name: nginx
    image: nginx:alpine

  source:
    repoURL: https://github.com/chrisXar/chrisrepo.git
    targetRevision: HEAD
    path: manifiestos-kubernetes
  destination: 
    server: https://kubernetes.default.svc
    namespace: chris

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true