apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/chrisXar/chrisrepo.git
    targetRevision: dev
    path: manifiestos-kubernetes/1/pod
  destination: 
    server: https://kubernetes.default.svc
    namespace: chris

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: false
      prune: false
